const router = require('express').Router();
const { register, login, logout, confirmEmail, resendVerification, getCurrentUser, completeGoogleLogin, changePassword, deleteAccount } = require('../controllers/auth.controller');
const { authLimiter } = require('../middleware/rateLimiter');
const { requireAuth } = require('../middleware/auth.middleware');
const { passport } = require('../config/passport');
const { requireGoogleOAuth, setOAuthState, verifyOAuthState } = require('../middleware/oauth.middleware');
const { asyncHandler } = require('../middleware/asyncHandler');
router.post('/register', authLimiter, asyncHandler(register));
router.post('/login', authLimiter, asyncHandler(login));
router.get('/verify-email', authLimiter, asyncHandler(confirmEmail));
router.post('/resend-verification', authLimiter, asyncHandler(resendVerification));
router.get('/me', requireAuth, asyncHandler(getCurrentUser));
router.post('/change-password', authLimiter, requireAuth, asyncHandler(changePassword));
router.delete('/me', authLimiter, requireAuth, asyncHandler(deleteAccount));
router.get('/google', authLimiter, requireGoogleOAuth, setOAuthState, (req, res, next) => passport.authenticate('google', { scope: ['profile', 'email'], session: false, state: res.locals.oauthState })(req, res, next));
router.get('/google/callback', authLimiter, requireGoogleOAuth, verifyOAuthState, passport.authenticate('google', { session: false, failureRedirect: '/api/auth/google' }), completeGoogleLogin);
router.post('/logout', asyncHandler(logout));
module.exports = router;